# Generated by Django 5.1.7 on 2025-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scripcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
